### ISSUE TITLE
[BUG]: Routing

### ISSUE THREAD

**Issue by unoctanium** [rio-labs/rio#148]
### Describe the bug

I try to test nested pages follpowing this how-to: `https://rio.dev/docs/howto/multiple-pages`.
But the deep pages (in my case URL `.../app/test1`) does not show up in the browser.

File: `app_page.py` in `/pages`

```
import rio
@rio.page(
    name = "App",
    url_segment = "app"
)
class AppPage (rio.Component):
    def build(self) -> rio.Component:
        return rio.Text("app")
```

I created a sub folder  `app_page` in `/pages` and placed a file there.
`pages/app_page/test1.py `

```
import rio
@rio.page(
    name="Test1",
    url_segment="test1",
)
class Test1(rio.Component):
    def build(self) -> rio.Component:
        return rio.Text("test1")
```

And this is my `__init.py__`
```
import rio
app = rio.App(
    name='app',
    build=lambda: rio.Column(
        rio.Text("Welcome to my app!"),
        rio.PageView(grow_y=True),
    ),
)
```

When I navigate to `http://<my_machine>/app`, I see the result of `app_page.py`

When I navigate to `http://<my_machine>/app/test1`, I also see the result of `app_page.py`, but expected the result of `test1.py`

Also, I can use any urls-segment behind /app/, like app/not-existing, and I don't get an error, but still the content of app_page.py 

Is it a bug or did I miss something?

P.S.: I run my webpage via  `rio run` 

### Steps to Reproduce

NA

### Operating System

Linux

### What browsers are you seeing the problem on?

Chrome

### What device are you using?

Desktop

**Comment by Aran-Fey** [comment]
The problem is that your app page doesn't contain a [`rio.PageView`](https://rio.dev/docs/api/pageview). PageViews are responsible for displaying sub-pages, but your app page only contains a `rio.Text`, so that's all you see.

I assume you want to display `rio.Text('app')` when the user visits `/app`, but not when they visit `/app/test1`. If that's the case, the easiest way to do it is to add another sub-page with the url segment `""`. So `app_page.py` would look like this:

```python
@rio.page(
    name="App",
    url_segment="app",
)
class AppPage(rio.Component):
    def build(self) -> rio.Component:
        return rio.PageView()
```

And then you'd put this in `app_page/app_root_page.py`:

```python
@rio.page(
    url_segment="",
)
class AppRootPage(rio.Component):
    def build(self) -> rio.Component:
        return rio.Text("app")
```

**Comment by unoctanium** [comment]
Confirm.
It works. It was a missunderstanding about how PageView() and routes play together.
Thank you very much.

**Comment by Sn3llius** [comment]
Thanks for your feedback, I'll update the HowTo.
